### ISSUE TITLE
Not available on hex?

### ISSUE THREAD

**Issue by lizziepaquette** [scripbox/firebase-admin-ex#5]
Hi, I'm interested in using this library but it seems like it hasn't been published to hex yet. Why not? Or is it and I just can't find it?

**Comment by nitinstp23** [comment]
We have not published this package to https://hex.pm yet.

Will update the Readme once it is published to Hex.

You can use this package via the `github` option in `mix.exs` file.

```elixir
{:firebase_admin_ex, github: "scripbox/firebase-admin-ex"},
```

**Comment by lizziepaquette** [comment]
Thanks for the info! What is the rational for not having published yet? Is it just documentation or are the apis going to change significantly? Should I be cautious about using this library in production?

**Comment by lizziepaquette** [comment]
Thanks for the info! What is the rational for not having published yet? Is it just documentation or are the apis going to change significantly? Should I be cautious about using this library in production?

**Comment by nitinstp23** [comment]
Done - https://hex.pm/packages/firebase_admin_ex
